### ISSUE TITLE
Try to rework or remove creation of regular expressions

### ISSUE THREAD

**Issue by Jacalz** [fredbi/uri#14]
There are a lot of very complicated regular expressions that not only are very hard to understand. Compiling all of these rules is slow and allocates quite a lot of memory. None of these are explicitly tested; just the functions making use of the expressions. Can we get rid of any of these? Can we simplify them? Can we lazy-load some of them?

```go
var (
	rexScheme   = regexp.MustCompile(`^[\p{L}][\p{L}\d\+-\.]+$`)
	rexFragment = regexp.MustCompile(`^([\p{L}\d\-\._~\:@!\$\&'\(\)\*\+,;=\?/]|(%[[:xdigit:]]{2})+)+$`)
	rexQuery    = rexFragment
	rexSegment  = regexp.MustCompile(`^([\p{L}\d\-\._~\:@!\$\&'\(\)\*\+,;=]|(%[[:xdigit:]]{2})+)+$`)
	rexHostname = regexp.MustCompile(`^[a-zA-Z0-9\p{L}]((-?[a-zA-Z0-9\p{L}]+)?|(([a-zA-Z0-9-\p{L}]{0,63})(\.)){1,6}([a-zA-Z\p{L}]){2,})$`)

	// unreserved | pct-encoded | sub-delims.
	rexRegname = regexp.MustCompile(`^([\p{L}\d\-\._~!\$\&'\(\)\*\+,;=]|(%[[:xdigit:]]{2})+)+$`)
	// unreserved | pct-encoded | sub-delims | ":".
	rexUserInfo = regexp.MustCompile(`^([\p{L}\d\-\._~\:!\$\&'\(\)\*\+,;=\?/]|(%[[:xdigit:]]{2})+)+$`)

	rexIPv6Zone = regexp.MustCompile(`:[^%:]+%25(([\p{L}\d\-\._~\:@!\$\&'\(\)\*\+,;=]|(%[[:xdigit:]]{2}))+)?$`)
)
```

Maybe the new [net/netip] package can be used to validate IPv6 instead of the regex?

**Comment by fredbi** [comment]
Hello  @Jacalz 

Indeed, the IP parser implemented by the standard library looks more efficient. I am taking a look at your remarks.

**Comment by fredbi** [comment]
@Jacalz  merged the enhancement following your suggestion.

Add to take it in several refactoring steps before removing all the regexps.

**Comment by Jacalz** [comment]
Thanks. Nice work. I'll have a look at that, and your ideas for breaking changes, later in the week :)
